version: '3.4'

services:
  api:
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ARCUS_HTTP_PORT=88"
      - "KeyVaultUri=https://<vault-name>.vault.azure.net/"
      - "Telemetry__ApplicationInsights__InstrumentationKey=ABC"
    ports:
      - "999:88"

  portal:
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=https://+:443;http://+:80"
      - "API_URL=http://localhost:88"
      - "KEYVAULT_ENDPOINT=https://<vault-name>.vault.azure.net/"
      - "KEYVAULT_AUTH_ID=<vault-client-id>"
      - "KEYVAULT_AUTH_SECRET=<vault-client-secret>"
    ports:
      - "998:80"
      - "888:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
