version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ARCUS_HTTP_PORT=88
      - Telemetry__ApplicationInsights__InstrumentationKey=ABC
    ports:
      - "999:88"

  portal:
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=https://+:443;http://+:80"
      - "KEYVAULT_ENDPOINT=https://hackthecrisis-kv.vault.azure.net/"
      - "KEYVAULT_AUTH_ID=24ae35b0-5c01-429f-b62c-d6da61d3d0eb"
      - "KEYVAULT_AUTH_SECRET=eRICg6=R2zHtSnJ7su-FS3bzPT]ZFTT_"
    ports:
      - "998:80"
      - "888:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
